name: testing
image: alpine

before_script:
    - apk update
    - apk add py3-pip
    - python3 -m venv venv
    - source venv/bin/activate
    - pip3 install -r requirements.txt

stages:
    - test

TestCode:
    stage: test

    script:
        - pytest
