on: [push]
jobs:
  testing:
    runs-on: alpine
    defaults:
      run: apk update
      run: apk add py3-pip
      run: python3 -m venv venv
      run: source venv/bin/activate
      run: pip3 install -r requirements.txt
    steps:
      - name: Run tests
        run: pytest

